[package]
name = "diffuse-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "diffuse_daemon"
path = "src/lib.rs"

[[bin]]
name = "diffuse"
path = "src/main.rs"

[dependencies]
diffuse-trust = { path = "../diffuse-trust" }
tokio.workspace = true
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
ed25519-dalek.workspace = true
rand.workspace = true
tonic.workspace = true
prost.workspace = true
serde_json.workspace = true
axum = "0.7"
bytemuck = "1"
hex = "0.4"
owo-colors = "4"
inquire = "0.7"
indicatif = "0.17"
console = "0.15"
tokio-stream = "0.1"
uuid = { version = "1.24.0", features = ["v4"] }
ratatui = "0.29"
crossterm = "0.28"

[build-dependencies]
tonic-build = "0.12"
